### ISSUE TITLE
Issue fixed mac-address

### ISSUE THREAD

**Issue by Urbanus001** [seb1992/aras-innovator-docker#5]
Thanks for your work!

Composing the Aras Innovator 2023 image works fine for me.
But Docker for windows does not set the mac-address to the fixed value added in the docker-compose.yml.
It alway set's the mac-address to a random value, when restarted the container.

So login from to Aras-web-client does not work due to invalid license key message. 

What is the solution for that problem? 
How to solve on a windows docker container? 

Thanks in advance!

**Comment by seb1992** [comment]
Hey,

glad the image works for you. Sounds like you almost have a working Innovator running!

Setting the MAC Address in the docker-compose.yml should work. The only exception I encountered is when Docker thinks the given MAC Address is invalid. What seems to always work for me is to use the MAC Address of my host machine ('ipconfig -all').

Good luck!
Sebastian

**Comment by Urbanus001** [comment]
Dear Sebastian, thanks for your answer.

I got it now! But I had to change the docker-compose.yml

Seems to be changed with newer Docker version:

```
services:
  server:
    image: arasinnovator2023
    platform: windows
    build:
        context: .\Server
        dockerfile: Dockerfile
    container_name: arasinnovator2023
    ports:
      - 80:80
      - 1433:1433
    # Set your mac adress on the line below, it has to match your License Key you specify in the InnovatorServerConfig.xml
    # You can request a license key here: https://www.aras.com/en/support/licensekeyservice  XX-XX-XX-XX-XX-XX
    networks:
        my_network:
            mac_address: XX-XX-XX-XX-XX-XX
    deploy:
      resources:
        limits:
          memory: 4000M
networks:
    my_network:
```
